# Form implementation generated from reading ui file 'D:\UEL\UEL\PROGRAMMING TECHNIQUES\MIDTERM\ui\BuyPopcorn.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(15, 23, 42);\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonTicket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTicket.setGeometry(QtCore.QRect(620, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTicket.setFont(font)
        self.pushButtonTicket.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/ic_ticket.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTicket.setIcon(icon)
        self.pushButtonTicket.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonTicket.setObjectName("pushButtonTicket")
        self.pushButtonBuyPop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBuyPop.setGeometry(QtCore.QRect(770, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBuyPop.setFont(font)
        self.pushButtonBuyPop.setStyleSheet("background-color: rgb(111, 56, 193);\n"
"color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/ic_popcorn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBuyPop.setIcon(icon1)
        self.pushButtonBuyPop.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBuyPop.setAutoRepeatDelay(305)
        self.pushButtonBuyPop.setObjectName("pushButtonBuyPop")
        self.pushButtonShwtm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonShwtm.setGeometry(QtCore.QRect(20, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShwtm.setFont(font)
        self.pushButtonShwtm.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonShwtm.setObjectName("pushButtonShwtm")
        self.pushButtonDiscounts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDiscounts.setGeometry(QtCore.QRect(550, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDiscounts.setFont(font)
        self.pushButtonDiscounts.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonDiscounts.setObjectName("pushButtonDiscounts")
        self.pushButtonEnterOp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEnterOp.setGeometry(QtCore.QRect(630, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEnterOp.setFont(font)
        self.pushButtonEnterOp.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonEnterOp.setObjectName("pushButtonEnterOp")
        self.pushButtonAboutUs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAboutUs.setGeometry(QtCore.QRect(800, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAboutUs.setFont(font)
        self.pushButtonAboutUs.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonAboutUs.setObjectName("pushButtonAboutUs")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, 891, 461))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 3012))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(100, 1500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setAcceptDrops(True)
        self.frame.setStyleSheet("    border: none")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 260, 191, 221))
        self.label_4.setStyleSheet("border-radius: 10px;")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/solo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(470, 260, 191, 221))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/couple.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setGeometry(QtCore.QRect(190, 100, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setMouseTracking(True)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(260, 430, 141, 41))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(30, 510, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 580, 181, 201))
        self.label_5.setStyleSheet("border-radius: 10px;")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/coke.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(350, 570, 181, 211))
        self.label_7.setStyleSheet("border-radius: 10px;")
        self.label_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_7.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/sprite.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(630, 570, 181, 211))
        self.label_8.setStyleSheet("border-radius: 10px;")
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_8.setText("")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/fanta.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(100, 780, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(380, 780, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(660, 780, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(670, 430, 141, 41))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_2.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setGeometry(QtCore.QRect(90, 820, 141, 41))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_9.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.widget_4 = QtWidgets.QWidget(parent=self.frame)
        self.widget_4.setGeometry(QtCore.QRect(370, 820, 141, 41))
        self.widget_4.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_9.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_15.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_15.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.widget_5 = QtWidgets.QWidget(parent=self.frame)
        self.widget_5.setGeometry(QtCore.QRect(650, 820, 141, 41))
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_16.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_16.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(640, 1200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(380, 1200, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.widget_6 = QtWidgets.QWidget(parent=self.frame)
        self.widget_6.setGeometry(QtCore.QRect(650, 1240, 141, 41))
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_19.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_19.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(30, 910, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(70, 980, 181, 221))
        self.label_21.setStyleSheet("border-radius: 10px;")
        self.label_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_21.setText("")
        self.label_21.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_21.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/org.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame)
        self.label_22.setGeometry(QtCore.QRect(350, 980, 181, 221))
        self.label_22.setStyleSheet("border-radius: 10px;")
        self.label_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_22.setText("")
        self.label_22.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_22.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/cheese.webp"))
        self.label_22.setScaledContents(True)
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame)
        self.label_23.setGeometry(QtCore.QRect(630, 980, 181, 221))
        self.label_23.setStyleSheet("border-radius: 10px;")
        self.label_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_23.setText("")
        self.label_23.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_23.setPixmap(QtGui.QPixmap("D:\\UEL\\UEL\\PROGRAMMING TECHNIQUES\\MIDTERM\\ui\\../images/caramel.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.frame)
        self.label_24.setGeometry(QtCore.QRect(80, 1200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.widget_7 = QtWidgets.QWidget(parent=self.frame)
        self.widget_7.setGeometry(QtCore.QRect(90, 1240, 141, 41))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_15.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_25.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_25.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.widget_8 = QtWidgets.QWidget(parent=self.frame)
        self.widget_8.setGeometry(QtCore.QRect(370, 1240, 141, 41))
        self.widget_8.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_26.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.label_26.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.frame)
        self.label_27.setGeometry(QtCore.QRect(260, 260, 151, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.frame)
        self.label_28.setGeometry(QtCore.QRect(670, 260, 151, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 911, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.pushButtonBuyPop_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBuyPop_2.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBuyPop_2.setFont(font)
        self.pushButtonBuyPop_2.setStyleSheet("background-color: rgb(111, 56, 193);\n"
"color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        self.pushButtonBuyPop_2.setIcon(icon1)
        self.pushButtonBuyPop_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBuyPop_2.setAutoRepeatDelay(305)
        self.pushButtonBuyPop_2.setObjectName("pushButtonBuyPop_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonTicket.setText(_translate("MainWindow", "BUY TICKETS"))
        self.pushButtonBuyPop.setText(_translate("MainWindow", "BUY POPCORN"))
        self.pushButtonShwtm.setText(_translate("MainWindow", "Showtimes"))
        self.pushButtonDiscounts.setText(_translate("MainWindow", "Discounts"))
        self.pushButtonEnterOp.setText(_translate("MainWindow", "Entertainment Options"))
        self.pushButtonAboutUs.setText(_translate("MainWindow", "About Us"))
        self.label_3.setText(_translate("MainWindow", "SELECT THE NEAREST THEATER"))
        self.comboBox.setItemText(0, _translate("MainWindow", "HCM"))
        self.comboBox.setItemText(1, _translate("MainWindow", "QUẬN CAM"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CỬU LONG THÀNH TRẠI"))
        self.comboBox.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(5, _translate("MainWindow", "New Item"))
        self.label_10.setText(_translate("MainWindow", "COMBO"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "BEVERAGES"))
        self.label_12.setText(_translate("MainWindow", "COKE    37.000VND"))
        self.label_13.setText(_translate("MainWindow", "SPRITE  37.000VND"))
        self.label_14.setText(_translate("MainWindow", "FANTA  37.000VND"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.pushButton_5.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "1"))
        self.pushButton_6.setText(_translate("MainWindow", "-"))
        self.pushButton_7.setText(_translate("MainWindow", "+"))
        self.label_9.setText(_translate("MainWindow", "1"))
        self.pushButton_8.setText(_translate("MainWindow", "-"))
        self.pushButton_9.setText(_translate("MainWindow", "+"))
        self.label_15.setText(_translate("MainWindow", "1"))
        self.pushButton_10.setText(_translate("MainWindow", "-"))
        self.pushButton_11.setText(_translate("MainWindow", "+"))
        self.label_16.setText(_translate("MainWindow", "1"))
        self.label_17.setText(_translate("MainWindow", "CARAMEL  60.000VND"))
        self.label_18.setText(_translate("MainWindow", "CHEESE  60.000"))
        self.pushButton_12.setText(_translate("MainWindow", "-"))
        self.pushButton_13.setText(_translate("MainWindow", "+"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "POPCORN"))
        self.label_24.setText(_translate("MainWindow", "ORIGINAL  50.000VND"))
        self.pushButton_14.setText(_translate("MainWindow", "-"))
        self.pushButton_15.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "1"))
        self.pushButton_16.setText(_translate("MainWindow", "-"))
        self.pushButton_17.setText(_translate("MainWindow", "+"))
        self.label_26.setText(_translate("MainWindow", "1"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>COMBO SOLO:<br/>1 Coke + 1 Pop</p><p>90.000VND</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>COMBO COUPLE:<br/>2 Coke + 1 Pop</p><p>110.000VND</p></body></html>"))
        self.pushButtonBuyPop_2.setText(_translate("MainWindow", "HOME"))
